name: flutter_app_store_server_receipt_utility
description: "The receipt utility for the App Store Server API."
version: 0.0.1
homepage: https://github.com/eternity1984/flutter_app_store_server_receipt_utility

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  pointycastle: ^3.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
